In [1]:
import pandas as pd
from tqdm import tqdm
from functools import partial
import joblib
import numpy as np
import faiss
import json
from sentence_transformers import SentenceTransformer
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

from src.data.preprocessing import clean_text
from src.data.vectorizer import get_vectorizer
from src.models.tfidf_logreg import get_model_v01
from src.models.tfidf_svm import get_model_v01 as get_svm_model_v01
from src.evaluation.metrics import evaluate, format_cm
from src.data.rac_utils import retrive_related, retrive_related_embedding
from src.data.retrieval_features import agument_data_optimized
from src.models.tfidf_xgboost import get_xgboost_model_v02

c:\Work\Project\ticket-nlp-classification\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
DATA_PATH = "../data/raw/all_tickets_processed_improved_v3.csv"
df = pd.read_csv(DATA_PATH)

X = df["Document"]
y = df["Topic_group"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, shuffle=True, random_state=2)

vectorizer: TfidfVectorizer = joblib.load("../artifacts/tfidf_vectorizer_v01.pkl")
lr_model: LogisticRegression = joblib.load("../artifacts/logreg_model_v01.pkl")
svm_model: LinearSVC = joblib.load("../artifacts/svm_model_v01.pkl")
xgboost_model: xgb.XGBClassifier = joblib.load("../artifacts/xgboost_v01.pkl")

with open("../artifacts/rac_corpus_similarity-euclidian_index_v01.json", 'r') as f:
    corpus = json.load(f)

index = faiss.read_index("../artifacts/traindata_similarity_index_v01.index")

retrieval_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

labelencoder: LabelEncoder = joblib.load("../artifacts/labelencoder_neural_v01.pkl")

In [3]:
X_train_agumented = await agument_data_optimized(
    texts=X_train.to_list(),
    vectorizer=vectorizer, retrieval_model=retrieval_model,
    index_path="../artifacts/traindata_similarity_index_v01.index",
    index_count=10,
    corpus=corpus, keys=["Document", "Topic_group"],
    y_key="Topic_group",
    classes=labelencoder.classes_,
    k=12,
    remove_top=False
)
X_train_agumented.shape

Batches: 100%|██████████| 1196/1196 [00:28<00:00, 42.66it/s]
100%|██████████| 3827/3827 [02:07<00:00, 29.90it/s]

(38269, 30010)

In [4]:
X_test_agumented = await agument_data_optimized(
    texts=X_test.to_list(),
    vectorizer=vectorizer, retrieval_model=retrieval_model,
    index_path="../artifacts/traindata_similarity_index_v01.index",
    index_count=10,
    corpus=corpus, keys=["Document", "Topic_group"],
    y_key="Topic_group",
    classes=labelencoder.classes_,
    k=12,
    remove_top=False
)
X_test_agumented.shape

Batches: 100%|██████████| 299/299 [00:07<00:00, 39.70it/s]
100%|██████████| 957/957 [00:31<00:00, 30.63it/s]

(9568, 30010)

In [5]:
y_train_encoded = labelencoder.transform(y_train)
y_test_encoded = labelencoder.transform(y_test)

In [6]:
model = get_xgboost_model_v02(len(labelencoder.classes_))

In [7]:
model.fit(
    X_train_agumented,
    y_train_encoded,
    eval_set = [(X_test_agumented, y_test_encoded)],
    verbose = True
)

[0]	validation_0-mlogloss:1.88698
[1]	validation_0-mlogloss:1.76925
[2]	validation_0-mlogloss:1.68439
[3]	validation_0-mlogloss:1.59514
[4]	validation_0-mlogloss:1.51671
[5]	validation_0-mlogloss:1.44616
[6]	validation_0-mlogloss:1.38785
[7]	validation_0-mlogloss:1.33091
[8]	validation_0-mlogloss:1.28062
[9]	validation_0-mlogloss:1.23457
[10]	validation_0-mlogloss:1.18985
[11]	validation_0-mlogloss:1.14989
[12]	validation_0-mlogloss:1.11106
[13]	validation_0-mlogloss:1.07759
[14]	validation_0-mlogloss:1.04363
[15]	validation_0-mlogloss:1.01221
[16]	validation_0-mlogloss:0.98347
[17]	validation_0-mlogloss:0.95635
[18]	validation_0-mlogloss:0.93015
[19]	validation_0-mlogloss:0.90623
[20]	validation_0-mlogloss:0.88368
[21]	validation_0-mlogloss:0.86226
[22]	validation_0-mlogloss:0.84264
[23]	validation_0-mlogloss:0.82422
[24]	validation_0-mlogloss:0.80709
[25]	validation_0-mlogloss:0.79078
[26]	validation_0-mlogloss:0.77534
[27]	validation_0-mlogloss:0.76074
[28]	validation_0-mlogloss:0.74696
[29]	validation_0-mlogloss:0.73421
[30]	validation_0-mlogloss:0.72213
[31]	validation_0-mlogloss:0.71061
[32]	validation_0-mlogloss:0.70052
[33]	validation_0-mlogloss:0.69052
[34]	validation_0-mlogloss:0.68175
[35]	validation_0-mlogloss:0.67256
[36]	validation_0-mlogloss:0.66346
[37]	validation_0-mlogloss:0.65507
[38]	validation_0-mlogloss:0.64753
[39]	validation_0-mlogloss:0.64048
[40]	validation_0-mlogloss:0.63354
[41]	validation_0-mlogloss:0.62668
[42]	validation_0-mlogloss:0.62082
[43]	validation_0-mlogloss:0.61487
[44]	validation_0-mlogloss:0.60948
[45]	validation_0-mlogloss:0.60467
[46]	validation_0-mlogloss:0.59959
[47]	validation_0-mlogloss:0.59503
[48]	validation_0-mlogloss:0.59076
[49]	validation_0-mlogloss:0.58607
[50]	validation_0-mlogloss:0.58217
[51]	validation_0-mlogloss:0.57890
[52]	validation_0-mlogloss:0.57529
[53]	validation_0-mlogloss:0.57184
[54]	validation_0-mlogloss:0.56882
[55]	validation_0-mlogloss:0.56624
[56]	validation_0-mlogloss:0.56326
[57]	validation_0-mlogloss:0.56087
[58]	validation_0-mlogloss:0.55866
[59]	validation_0-mlogloss:0.55630
[60]	validation_0-mlogloss:0.55441
[61]	validation_0-mlogloss:0.55241
[62]	validation_0-mlogloss:0.55062
[63]	validation_0-mlogloss:0.54883
[64]	validation_0-mlogloss:0.54737
[65]	validation_0-mlogloss:0.54591
[66]	validation_0-mlogloss:0.54404
[67]	validation_0-mlogloss:0.54206
[68]	validation_0-mlogloss:0.54060
[69]	validation_0-mlogloss:0.53926
[70]	validation_0-mlogloss:0.53816
[71]	validation_0-mlogloss:0.53730
[72]	validation_0-mlogloss:0.53646
[73]	validation_0-mlogloss:0.53543
[74]	validation_0-mlogloss:0.53461
[75]	validation_0-mlogloss:0.53400
[76]	validation_0-mlogloss:0.53339
[77]	validation_0-mlogloss:0.53297
[78]	validation_0-mlogloss:0.53287
[79]	validation_0-mlogloss:0.53247
[80]	validation_0-mlogloss:0.53238
[81]	validation_0-mlogloss:0.53146
[82]	validation_0-mlogloss:0.53087
[83]	validation_0-mlogloss:0.53072
[84]	validation_0-mlogloss:0.53054
[85]	validation_0-mlogloss:0.53022
[86]	validation_0-mlogloss:0.53039
[87]	validation_0-mlogloss:0.52977
[88]	validation_0-mlogloss:0.52967
[89]	validation_0-mlogloss:0.52964
[90]	validation_0-mlogloss:0.52917
[91]	validation_0-mlogloss:0.52914
[92]	validation_0-mlogloss:0.52884
[93]	validation_0-mlogloss:0.52895
[94]	validation_0-mlogloss:0.52908
[95]	validation_0-mlogloss:0.52904
[96]	validation_0-mlogloss:0.52903
[97]	validation_0-mlogloss:0.52911
[98]	validation_0-mlogloss:0.52979
[99]	validation_0-mlogloss:0.52990
[100]	validation_0-mlogloss:0.53046
[101]	validation_0-mlogloss:0.53070
[102]	validation_0-mlogloss:0.53113
[103]	validation_0-mlogloss:0.53119
[104]	validation_0-mlogloss:0.53124
[105]	validation_0-mlogloss:0.53124
[106]	validation_0-mlogloss:0.53165
[107]	validation_0-mlogloss:0.53221
[108]	validation_0-mlogloss:0.53293
[109]	validation_0-mlogloss:0.53315
[110]	validation_0-mlogloss:0.53377
[111]	validation_0-mlogloss:0.53353
[112]	validation_0-mlogloss:0.53434
[113]	validation_0-mlogloss:0.53480
[114]	validation_0-mlogloss:0.53525
[115]	validation_0-mlogloss:0.53587
[116]	validation_0-mlogloss:0.53620
[117]	validation_0-mlogloss:0.53663
[118]	validation_0-mlogloss:0.53712
[119]	validation_0-mlogloss:0.53766
[120]	validation_0-mlogloss:0.53864
[121]	validation_0-mlogloss:0.53880
[122]	validation_0-mlogloss:0.53922
[123]	validation_0-mlogloss:0.53933
[124]	validation_0-mlogloss:0.54028
[125]	validation_0-mlogloss:0.54077
[126]	validation_0-mlogloss:0.54173
[127]	validation_0-mlogloss:0.54175
[128]	validation_0-mlogloss:0.54287
[129]	validation_0-mlogloss:0.54405
[130]	validation_0-mlogloss:0.54500
[131]	validation_0-mlogloss:0.54630
[132]	validation_0-mlogloss:0.54682
[133]	validation_0-mlogloss:0.54766
[134]	validation_0-mlogloss:0.54833
[135]	validation_0-mlogloss:0.54892
[136]	validation_0-mlogloss:0.54962
[137]	validation_0-mlogloss:0.55066
[138]	validation_0-mlogloss:0.55096
[139]	validation_0-mlogloss:0.55195
[140]	validation_0-mlogloss:0.55303
[141]	validation_0-mlogloss:0.55404
[142]	validation_0-mlogloss:0.55512
[143]	validation_0-mlogloss:0.55612
[144]	validation_0-mlogloss:0.55656
[145]	validation_0-mlogloss:0.55730
[146]	validation_0-mlogloss:0.55781
[147]	validation_0-mlogloss:0.55905
[148]	validation_0-mlogloss:0.55944
[149]	validation_0-mlogloss:0.56050
[150]	validation_0-mlogloss:0.56112
[151]	validation_0-mlogloss:0.56172
[152]	validation_0-mlogloss:0.56254
[153]	validation_0-mlogloss:0.56355
[154]	validation_0-mlogloss:0.56458
[155]	validation_0-mlogloss:0.56491
[156]	validation_0-mlogloss:0.56557
[157]	validation_0-mlogloss:0.56650
[158]	validation_0-mlogloss:0.56749
[159]	validation_0-mlogloss:0.56887
[160]	validation_0-mlogloss:0.56983
[161]	validation_0-mlogloss:0.57052
[162]	validation_0-mlogloss:0.57112
[163]	validation_0-mlogloss:0.57205
[164]	validation_0-mlogloss:0.57274
[165]	validation_0-mlogloss:0.57339
[166]	validation_0-mlogloss:0.57399
[167]	validation_0-mlogloss:0.57458
[168]	validation_0-mlogloss:0.57520
[169]	validation_0-mlogloss:0.57565
[170]	validation_0-mlogloss:0.57606
[171]	validation_0-mlogloss:0.57723
[172]	validation_0-mlogloss:0.57816
[173]	validation_0-mlogloss:0.57903
[174]	validation_0-mlogloss:0.57976
[175]	validation_0-mlogloss:0.58043
[176]	validation_0-mlogloss:0.58083
[177]	validation_0-mlogloss:0.58149
[178]	validation_0-mlogloss:0.58190
[179]	validation_0-mlogloss:0.58306
[180]	validation_0-mlogloss:0.58425
[181]	validation_0-mlogloss:0.58536
[182]	validation_0-mlogloss:0.58603
[183]	validation_0-mlogloss:0.58698
[184]	validation_0-mlogloss:0.58786
[185]	validation_0-mlogloss:0.58882
[186]	validation_0-mlogloss:0.58964
[187]	validation_0-mlogloss:0.59052
[188]	validation_0-mlogloss:0.59116
[189]	validation_0-mlogloss:0.59228
[190]	validation_0-mlogloss:0.59313
[191]	validation_0-mlogloss:0.59415
[192]	validation_0-mlogloss:0.59501
[193]	validation_0-mlogloss:0.59583
[194]	validation_0-mlogloss:0.59668
[195]	validation_0-mlogloss:0.59722
[196]	validation_0-mlogloss:0.59839
[197]	validation_0-mlogloss:0.59902
[198]	validation_0-mlogloss:0.59987
[199]	validation_0-mlogloss:0.60036
[200]	validation_0-mlogloss:0.60061
[201]	validation_0-mlogloss:0.60160
[202]	validation_0-mlogloss:0.60261
[203]	validation_0-mlogloss:0.60383
[204]	validation_0-mlogloss:0.60482
[205]	validation_0-mlogloss:0.60582
[206]	validation_0-mlogloss:0.60672
[207]	validation_0-mlogloss:0.60793
[208]	validation_0-mlogloss:0.60880
[209]	validation_0-mlogloss:0.60952
[210]	validation_0-mlogloss:0.61037
[211]	validation_0-mlogloss:0.61115
[212]	validation_0-mlogloss:0.61193
[213]	validation_0-mlogloss:0.61293
[214]	validation_0-mlogloss:0.61393
[215]	validation_0-mlogloss:0.61438
[216]	validation_0-mlogloss:0.61507
[217]	validation_0-mlogloss:0.61574
[218]	validation_0-mlogloss:0.61631
[219]	validation_0-mlogloss:0.61735
[220]	validation_0-mlogloss:0.61805
[221]	validation_0-mlogloss:0.61878
[222]	validation_0-mlogloss:0.61961
[223]	validation_0-mlogloss:0.62019
[224]	validation_0-mlogloss:0.62098
[225]	validation_0-mlogloss:0.62174
[226]	validation_0-mlogloss:0.62274
[227]	validation_0-mlogloss:0.62345
[228]	validation_0-mlogloss:0.62452
[229]	validation_0-mlogloss:0.62516
[230]	validation_0-mlogloss:0.62590
[231]	validation_0-mlogloss:0.62627
[232]	validation_0-mlogloss:0.62668
[233]	validation_0-mlogloss:0.62738
[234]	validation_0-mlogloss:0.62787
[235]	validation_0-mlogloss:0.62875
[236]	validation_0-mlogloss:0.62959
[237]	validation_0-mlogloss:0.63028
[238]	validation_0-mlogloss:0.63113
[239]	validation_0-mlogloss:0.63149
[240]	validation_0-mlogloss:0.63174
[241]	validation_0-mlogloss:0.63221
[242]	validation_0-mlogloss:0.63270
[243]	validation_0-mlogloss:0.63309
[244]	validation_0-mlogloss:0.63367
[245]	validation_0-mlogloss:0.63408
[246]	validation_0-mlogloss:0.63493
[247]	validation_0-mlogloss:0.63552
[248]	validation_0-mlogloss:0.63604
[249]	validation_0-mlogloss:0.63665
[250]	validation_0-mlogloss:0.63725
[251]	validation_0-mlogloss:0.63779
[252]	validation_0-mlogloss:0.63834
[253]	validation_0-mlogloss:0.63897
[254]	validation_0-mlogloss:0.63937
[255]	validation_0-mlogloss:0.63955
[256]	validation_0-mlogloss:0.64009
[257]	validation_0-mlogloss:0.64040
[258]	validation_0-mlogloss:0.64109
[259]	validation_0-mlogloss:0.64154
[260]	validation_0-mlogloss:0.64191
[261]	validation_0-mlogloss:0.64202
[262]	validation_0-mlogloss:0.64240
[263]	validation_0-mlogloss:0.64333
[264]	validation_0-mlogloss:0.64357
[265]	validation_0-mlogloss:0.64387
[266]	validation_0-mlogloss:0.64419
[267]	validation_0-mlogloss:0.64505
[268]	validation_0-mlogloss:0.64542
[269]	validation_0-mlogloss:0.64553
[270]	validation_0-mlogloss:0.64608
[271]	validation_0-mlogloss:0.64639
[272]	validation_0-mlogloss:0.64669
[273]	validation_0-mlogloss:0.64701
[274]	validation_0-mlogloss:0.64734
[275]	validation_0-mlogloss:0.64771
[276]	validation_0-mlogloss:0.64803
[277]	validation_0-mlogloss:0.64830
[278]	validation_0-mlogloss:0.64902
[279]	validation_0-mlogloss:0.64978
[280]	validation_0-mlogloss:0.64998
[281]	validation_0-mlogloss:0.65028
[282]	validation_0-mlogloss:0.65069
[283]	validation_0-mlogloss:0.65140
[284]	validation_0-mlogloss:0.65219
[285]	validation_0-mlogloss:0.65242
[286]	validation_0-mlogloss:0.65303
[287]	validation_0-mlogloss:0.65364
[288]	validation_0-mlogloss:0.65378
[289]	validation_0-mlogloss:0.65423
[290]	validation_0-mlogloss:0.65452
[291]	validation_0-mlogloss:0.65454
[292]	validation_0-mlogloss:0.65473
[293]	validation_0-mlogloss:0.65477
[294]	validation_0-mlogloss:0.65480
[295]	validation_0-mlogloss:0.65508
[296]	validation_0-mlogloss:0.65534
[297]	validation_0-mlogloss:0.65575
[298]	validation_0-mlogloss:0.65602
[299]	validation_0-mlogloss:0.65610

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=8, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=6, num_class=8, ...)

In [8]:
y_pred = model.predict(X_test_agumented)
format_cm(evaluate(y_test_encoded, y_pred), class_names=list(labelencoder.classes_), normalize=True)

              precision    recall  f1-score   support

           0     0.8966    0.8884    0.8925      1425
           1     0.8170    0.7358    0.7743       352
           2     0.8319    0.8639    0.8476      2183
           3     0.8325    0.8392    0.8358      2724
           4     0.8354    0.7783    0.8059       424
           5     0.8107    0.8038    0.8073      1412
           6     0.9153    0.8986    0.9069       493
           7     0.8867    0.8739    0.8802       555

    accuracy                         0.8455      9568
   macro avg     0.8533    0.8352    0.8438      9568
weighted avg     0.8457    0.8455    0.8454      9568

,Pred: Access,Pred: Administrative rights,Pred: HR Support,Pred: Hardware,Pred: Internal Project,Pred: Miscellaneous,Pred: Purchase,Pred: Storage
True: Access,0.888421,0.002105,0.035088,0.042807,0.004912,0.021053,0.002105,0.003509
True: Administrative rights,0.019886,0.735795,0.031250,0.178977,0.002841,0.014205,0.011364,0.005682
True: HR Support,0.014659,0.003665,0.863949,0.060467,0.009620,0.042602,0.000916,0.004123
True: Hardware,0.024229,0.011013,0.060206,0.839207,0.007709,0.038179,0.009912,0.009545
True: Internal Project,0.021226,0.004717,0.084906,0.049528,0.778302,0.049528,0.002358,0.009434
True: Miscellaneous,0.014873,0.006374,0.067989,0.084986,0.008499,0.803824,0.002833,0.010623
True: Purchase,0.006085,0.002028,0.018256,0.058824,0.006085,0.008114,0.898580,0.002028
True: Storage,0.014414,0.009009,0.027027,0.061261,0.000000,0.014414,0.000000,0.873874

In [9]:
from src.models.tfidf_logreg import get_model_v01
from src.models.tfidf_svm import get_model_v01 as get_svm_model_v01

In [14]:
lr_model = get_model_v01()
lr_model.fit(X_train_agumented, y_train_encoded)

LogisticRegression(max_iter=1000)

In [15]:
y_pred_lr = lr_model.predict(X_test_agumented)
format_cm(evaluate(y_test_encoded, y_pred_lr), class_names=list(labelencoder.classes_), normalize=True)

              precision    recall  f1-score   support

           0     0.9109    0.8891    0.8999      1425
           1     0.8489    0.7500    0.7964       352
           2     0.8648    0.8759    0.8703      2183
           3     0.8425    0.8796    0.8606      2724
           4     0.8597    0.7948    0.8260       424
           5     0.8320    0.8208    0.8264      1412
           6     0.9236    0.9067    0.9150       493
           7     0.9077    0.8865    0.8970       555

    accuracy                         0.8648      9568
   macro avg     0.8737    0.8504    0.8614      9568
weighted avg     0.8652    0.8648    0.8646      9568

,Pred: Access,Pred: Administrative rights,Pred: HR Support,Pred: Hardware,Pred: Internal Project,Pred: Miscellaneous,Pred: Purchase,Pred: Storage
True: Access,0.889123,0.002807,0.032982,0.044211,0.006316,0.019649,0.001404,0.003509
True: Administrative rights,0.019886,0.750000,0.025568,0.176136,0.002841,0.014205,0.008523,0.002841
True: HR Support,0.010536,0.001832,0.875859,0.059551,0.006413,0.038021,0.001832,0.005955
True: Hardware,0.019824,0.011380,0.042217,0.879589,0.004405,0.030470,0.006975,0.005140
True: Internal Project,0.021226,0.007075,0.066038,0.056604,0.794811,0.047170,0.002358,0.004717
True: Miscellaneous,0.014873,0.001416,0.055949,0.080737,0.010623,0.820822,0.005666,0.009915
True: Purchase,0.006085,0.002028,0.016227,0.048682,0.008114,0.010142,0.906694,0.002028
True: Storage,0.012613,0.003604,0.023423,0.055856,0.000000,0.018018,0.000000,0.886486

In [16]:
svm_model = get_svm_model_v01()
svm_model.fit(X_train_agumented, y_train_encoded)

y_pred_svm = svm_model.predict(X_test_agumented)

In [17]:
format_cm(evaluate(y_test_encoded, y_pred_svm), class_names=list(labelencoder.classes_), normalize=True)

              precision    recall  f1-score   support

           0     0.9181    0.9046    0.9113      1425
           1     0.8459    0.7642    0.8030       352
           2     0.8773    0.8814    0.8793      2183
           3     0.8554    0.8862    0.8705      2724
           4     0.8589    0.8184    0.8382       424
           5     0.8515    0.8407    0.8460      1412
           6     0.9143    0.9087    0.9115       493
           7     0.9208    0.9009    0.9107       555

    accuracy                         0.8756      9568
   macro avg     0.8803    0.8631    0.8713      9568
weighted avg     0.8758    0.8756    0.8755      9568

,Pred: Access,Pred: Administrative rights,Pred: HR Support,Pred: Hardware,Pred: Internal Project,Pred: Miscellaneous,Pred: Purchase,Pred: Storage
True: Access,0.904561,0.002807,0.026667,0.037895,0.004912,0.018246,0.001404,0.003509
True: Administrative rights,0.014205,0.764205,0.022727,0.161932,0.002841,0.014205,0.019886,0.000000
True: HR Support,0.010994,0.002290,0.881356,0.055428,0.006413,0.036647,0.002290,0.004581
True: Hardware,0.018355,0.010279,0.040749,0.886197,0.005140,0.026432,0.008076,0.004772
True: Internal Project,0.021226,0.007075,0.056604,0.054245,0.818396,0.033019,0.002358,0.007075
True: Miscellaneous,0.014164,0.003541,0.046742,0.071530,0.011331,0.840652,0.003541,0.008499
True: Purchase,0.004057,0.004057,0.018256,0.048682,0.010142,0.006085,0.908722,0.000000
True: Storage,0.009009,0.003604,0.023423,0.050450,0.000000,0.012613,0.000000,0.900901

In [27]:
set(y_train.to_list())

{'Access',
 'Administrative rights',
 'HR Support',
 'Hardware',
 'Internal Project',
 'Miscellaneous',
 'Purchase',
 'Storage'}

In [28]:
y_train.to_list()[0]

'Hardware'

In [29]:
X_train.to_list()[0]

'unable to connect to unable connect hi longer able connect was working earlier morning please can you urgently advise working active bid need update files share point can following logs warning used setting maximum version options error ca fails with such file or directory options error please correct these errors use help for more information client manager'